name: UFEMISM Test Suite - compile and cache UFEMISM (development build) on MacOS
run-name: ${{ github.actor }} - UFEMISM Test Suite - compile and cache UFEMISM (development build) on MacOS
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compile_UFEMISM_dev:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran
          brew install cmake
          brew install ninja

      - name: Set up Fortran compiler          # See: https://github.com/marketplace/actions/setup-fortran
        uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: Verify compiler setup
        run: gfortran --version

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Update submodules (UPSY, LADDIE, data)
        run: |
          git submodule update --init --remote

      - name: Compile UFEMISM
        run: ./compile_UFEMISM.csh  dev  clean

      - name: Cache UFEMISM program
        uses: actions/cache/save@v3
        id: UFEMISM_program_cache_save
        with:
          path: UFEMISM_program
          key: UFEMISM_program_dev_${{ github.ref_name }}_${{ github.run_id }}
