name: UFEMISM Test Suite - run and analyse integrated test - idealised/Halfar_dome/Halfar_5km
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated test - idealised/Halfar_dome/Halfar_5km
on:
  workflow_call:

jobs:
  job_main:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated test - idealised/Halfar_dome/Halfar_5km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_5km/config.cfg

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Analyse integrated test - idealised/Halfar_dome/Halfar_5km
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_5km')
            analyse_integrated_test('${{github.workspace}}/automated_testing')

      # - name: Upload output as artifacts
      #   uses: actions/upload-artifact@v4.3.4
      #   with:
      #     name: results_component_tests
      #     path: automated_testing/component_tests/results
