name: UFEMISM Test Suite - run and analyse integrated test - idealised/Halfar_dome/Halfar_10km
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated test - idealised/Halfar_dome/Halfar_10km
on:
  workflow_call:

jobs:
  Halfar_10km:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated test - idealised/Halfar_dome/Halfar_10km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_10km/config.cfg

      - name: Upload output as artifacts
        uses: actions/upload-artifact@v4.3.4
        with:
          name: results_integrated_test_idealised_Halfar_dome_Halfar_10km
          path: automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_10km/results
