# NOTE: this script is created automatically by running
# 'automated_testing/integrated_tests/add_all_integrated_tests_to_Github_workflow.m'

name: UFEMISM Test Suite - run and analyse integrated_tests/idealised/SSA_icestream
run-name: ${{ github.actor }} - UFEMISM Test Suite - run and analyse integrated_tests/idealised/SSA_icestream
on:
  workflow_call:

jobs:
  SSA_icestream:
    runs-on: macos-latest
    steps:

      - name: Install packages with Homebrew   # Packages end up in /opt/homebrew/Cellar
        run: |
          #brew install gcc                    # Not needed on GitHub server, already installed
          brew install open-mpi
          brew install petsc
          brew unlink hdf5-mpi                 # To fix the following conflict: "hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other"
          brew install netcdf
          brew install netcdf-fortran

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2.2.0
        with:
          cache: true

      - name: Checkout UFEMISM repository
        uses: actions/checkout@v4

      - name: Update submodules (UPSY, LADDIE, data)
        run: |
          git submodule update --init --remote

      - name: Restore UFEMISM program from cache
        uses: actions/cache/restore@v3
        id: UFEMISM_program_cache_restore
        with:
          path: UFEMISM_program
          key: UFEMISM_program_perf_${{ github.ref_name }}_${{ github.run_id }}

      - name: Run integrated_tests/idealised/SSA_icestream - 01_32km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/SSA_icestream/config_01_32km.cfg

      - name: Run integrated_tests/idealised/SSA_icestream - 02_16km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/SSA_icestream/config_02_16km.cfg

      - name: Run integrated_tests/idealised/SSA_icestream - 03_8km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/SSA_icestream/config_03_8km.cfg

      - name: Run integrated_tests/idealised/SSA_icestream - 04_4km
        run: mpiexec  -n 2  UFEMISM_program  automated_testing/integrated_tests/idealised/SSA_icestream/config_04_4km.cfg

      - name: Analyse integrated_tests/idealised/SSA_icestream
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath('automated_testing/integrated_tests/idealised/SSA_icestream')
            analyse_integrated_test('${{github.workspace}}/automated_testing')

      - name: Upload scoreboard file as artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: scoreboard_file_integrated_tests_idealised_SSA_icestream
          path: automated_testing/scoreboard/temporary_scoreboard_files/*.xml
